### ISSUE TITLE
October YunoHost Community News Planning

### ISSUE THREAD

**Issue by decentral1se** [YunoHost/news#1]
See https://forum.yunohost.org/t/october-yunohost-community-news-planning/9191.

**Comment by decentral1se** [comment]
* https://social.logilab.org/@arthurlutz/102904482336325351
* Grab some news from https://pad.lqdn.fr/p/yunohost-01-10-2019
* YunoHost workshop @ https://www.webassoc.org/events/libre-191119/
* YunoHost workshop @ https://selbstgemacht-diy.blogspot.com/

**Comment by decentral1se** [comment]
* https://donate.yunohost.org is out
* New app releases, new apps in general? Discourse, NextCloud, Mailman3 and what else?
* Lead up to 3.7, permissions work, bug fixes, etc.
* On-going work with Buster and shout out to Q&A testers
* Shout out to @unklebonehead for pushing us to do this ;)
* New posts/blog stuff from https://posts.boneheadmedia.com/

**Comment by alexAubin** [comment]
>New app releases, new apps in general? Discourse, NextCloud, Mailman3 and what else?

Idk if that helps but there's this RSS feed https://dash.yunohost.org/appsobservatory/rss that summarize every 1st and 15th day what happened in the app catalog

**Comment by decentral1se** [comment]
New release:

> https://forum.yunohost.org/t/yunohost-3-6-release-sortie-de-yunohost-3-6/8359/61

**Comment by unklebonehead** [comment]
Just fyi I am changing that url. Going back to static html site. Just cant decide if I want use my own server or use hugo/netlify/github. So the url will just be https://boneheadmedia.com

**Comment by unklebonehead** [comment]
I forked this so I can write posts too.
https://github.com/unklebonehead/news

**Comment by decentral1se** [comment]
OK, closing this off for now and will prepare a PR for the new post.
